name: java-app

on: push

jobs:
  java_build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: "17"
      - run: java Simple.java        
            
